[package]
name = "rpi_pwm"
version = "0.1.0"
authors = ["chrism <christophermoran@ucsb.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
simple-signal = "1.1.1"